model:
  num_classes: 2
  num_frames: 8
  embed_dims: 512
  num_heads: 8
  ff_dim: 2048
  num_transformer_layers: 4
  dropout_rate: 0.1
  use_spatial_attention: true

data:
  data_dir: "D:\\dataset"
  batch_size: 32
  num_frames: 8
  frame_size: [299, 299]
  normalize: true

training:
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
