model:
  num_classes: 1
  num_frames: 4
  embed_dims: 256
  num_heads: 8
  ff_dim: 1024
  num_transformer_layers: 3
  dropout_rate: 0.1
  use_spatial_attention: true

data:
  data_dir: "/kaggle/input/celeb-df/dataset"
  batch_size: 8
  num_frames: 4
  frame_size: [299, 299]
  normalize: true

training:
  epochs: 50
  learning_rate: 0.001
  fine-tune_lr: 0.0001
  freeze_epochs: 5
  optimizer: "adam"
  loss: "binary_crossentropy"
  metrics: ["accuracy"]
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
